spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB